[Variables]
Font=Segoe UI
; Colors
Background=255,255,255,1
DefaultFontColor=255, 255, 255

; Sizes
; Scalefactor determines how much the skins need to be scaled, to provide compatibility with Windows DPI settings.
; Set 1.25 for 125% scaling, 1.5 for 150% etc.
Scalefactor=1.75

; Styles
[styleTextTitle]
StringAlign=Left
FontSize=(19*#Scalefactor#)
FontColor=#DefaultFontColor#
FontFace=#FontSegoe#
StringStyle=Bold
AntiAlias=1
ClipString=1

[styleText]
StringAlign=Left
FontSize=(11*#Scalefactor#)
FontColor=#SubtitleColor#
FontFace=#Font#
AntiAlias=1
ClipString=1

[styleTextBold]
StringAlign=Left
FontSize=(12*#Scalefactor#)
FontColor=#DefaultFontColor#
FontFace=#FontSegoe#
StringStyle=Bold
AntiAlias=1
ClipString=1