[Variables]
disk1=C:
disk2=D:
disk3=E:
disk4=F:
disk5=G:
disk6=H:
disk7=I:
disk8=J:
disk9=K:
disk10=L:

; Disk 1
[measureTitleDisk1]
Measure=FreeDiskSpace
Drive=#disk1#
Label=1
Update=-1

[measureTotalDisk1]
Measure=FreeDiskSpace
Drive=#disk1#
Total=1
UpdateDivider=120

[measureUsedDisk1]
Measure=FreeDiskSpace
Drive=#disk1#
InvertMeasure=1
UpdateDivider=120

[measureFreeDisk1]
Measure=FreeDiskSpace
Drive=#disk1#
UpdateDivider=120

; Disk 2
[measureTitleDisk2]
Measure=FreeDiskSpace
Drive=#disk2#
Label=1
Update=-1

[measureTotalDisk2]
Measure=FreeDiskSpace
Drive=#disk2#
Total=1
UpdateDivider=120

[measureUsedDisk2]
Measure=FreeDiskSpace
Drive=#disk2#
InvertMeasure=1
UpdateDivider=120

[measureFreeDisk2]
Measure=FreeDiskSpace
Drive=#disk2#
UpdateDivider=120

; Disk 3
[measureTitleDisk3]
Measure=FreeDiskSpace
Drive=#disk3#
Label=1
Update=-1

[measureTotalDisk3]
Measure=FreeDiskSpace
Drive=#disk3#
Total=1
UpdateDivider=120

[measureUsedDisk3]
Measure=FreeDiskSpace
Drive=#disk3#
InvertMeasure=1
UpdateDivider=120

[measureFreeDisk3]
Measure=FreeDiskSpace
Drive=#disk3#
UpdateDivider=120

; Disk 4
[measureTitleDisk4]
Measure=FreeDiskSpace
Drive=#disk4#
Label=1
Update=-1

[measureTotalDisk4]
Measure=FreeDiskSpace
Drive=#disk4#
Total=1
UpdateDivider=120

[measureUsedDisk4]
Measure=FreeDiskSpace
Drive=#disk4#
InvertMeasure=1
UpdateDivider=120

[measureFreeDisk4]
Measure=FreeDiskSpace
Drive=#disk4#
UpdateDivider=120

; Disk 5
[measureTitleDisk5]
Measure=FreeDiskSpace
Drive=#disk5#
Label=1
Update=-1

[measureTotalDisk5]
Measure=FreeDiskSpace
Drive=#disk5#
Total=1
UpdateDivider=120

[measureUsedDisk5]
Measure=FreeDiskSpace
Drive=#disk5#
InvertMeasure=1
UpdateDivider=120

[measureFreeDisk5]
Measure=FreeDiskSpace
Drive=#disk5#
UpdateDivider=120

; Disk 6
[measureTitleDisk6]
Measure=FreeDiskSpace
Drive=#disk6#
Label=1
Update=-1

[measureTotalDisk6]
Measure=FreeDiskSpace
Drive=#disk6#
Total=1
UpdateDivider=120

[measureUsedDisk6]
Measure=FreeDiskSpace
Drive=#disk6#
InvertMeasure=1
UpdateDivider=120

[measureFreeDisk6]
Measure=FreeDiskSpace
Drive=#disk6#
UpdateDivider=120

; Disk 7
[measureTitleDisk7]
Measure=FreeDiskSpace
Drive=#disk7#
Label=1
Update=-1

[measureTotalDisk7]
Measure=FreeDiskSpace
Drive=#disk7#
Total=1
UpdateDivider=120

[measureUsedDisk7]
Measure=FreeDiskSpace
Drive=#disk7#
InvertMeasure=1
UpdateDivider=120

[measureFreeDisk7]
Measure=FreeDiskSpace
Drive=#disk7#
UpdateDivider=120

; Disk 8
[measureTitleDisk8]
Measure=FreeDiskSpace
Drive=#disk8#
Label=1
Update=-1

[measureTotalDisk8]
Measure=FreeDiskSpace
Drive=#disk8#
Total=1
UpdateDivider=120

[measureUsedDisk8]
Measure=FreeDiskSpace
Drive=#disk8#
InvertMeasure=1
UpdateDivider=120

[measureFreeDisk8]
Measure=FreeDiskSpace
Drive=#disk8#
UpdateDivider=120