[Variables]
disk1=C:
disk2=D:
disk3=E:
disk4=F:
disk5=G:
disk6=H:
disk7=I:
disk8=J:
disk9=K:

[measureTitleDisk1]
Measure=FreeDiskSpace
Drive=#disk1#
Label=1
Update=-1

[measureTotalDisk1]
Measure=FreeDiskSpace
Drive=#disk1#
Total=1
UpdateDivider=120

[measureUsedDisk1]
Measure=FreeDiskSpace
Drive=#disk1#
InvertMeasure=1
UpdateDivider=120

[measureTitleDisk2]
Measure=FreeDiskSpace
Drive=#disk2#
Label=1
Update=-1

[measureTotalDisk2]
Measure=FreeDiskSpace
Drive=#disk2#
Total=1
UpdateDivider=120

[measureUsedDisk2]
Measure=FreeDiskSpace
Drive=#disk2#
InvertMeasure=1
UpdateDivider=120

[measureTitleDisk3]
Measure=FreeDiskSpace
Drive=#disk3#
Label=1
Update=-1

[measureTotalDisk3]
Measure=FreeDiskSpace
Drive=#disk3#
Total=1
UpdateDivider=120

[measureUsedDisk3]
Measure=FreeDiskSpace
Drive=#disk3#
InvertMeasure=1
UpdateDivider=120

[measureTitleDisk4]
Measure=FreeDiskSpace
Drive=#disk4#
Label=1
Update=-1

[measureTotalDisk4]
Measure=FreeDiskSpace
Drive=#disk4#
Total=1
UpdateDivider=120

[measureUsedDisk4]
Measure=FreeDiskSpace
Drive=#disk4#
InvertMeasure=1
UpdateDivider=120

[measureTitleDisk5]
Measure=FreeDiskSpace
Drive=#disk5#
Label=1
Update=-1

[measureTotalDisk5]
Measure=FreeDiskSpace
Drive=#disk5#
Total=1
UpdateDivider=120

[measureUsedDisk5]
Measure=FreeDiskSpace
Drive=#disk5#
InvertMeasure=1
UpdateDivider=120

[measureTitleDisk6]
Measure=FreeDiskSpace
Drive=#disk6#
Label=1
Update=-1

[measureTotalDisk6]
Measure=FreeDiskSpace
Drive=#disk6#
Total=1
UpdateDivider=120

[measureUsedDisk6]
Measure=FreeDiskSpace
Drive=#disk6#
InvertMeasure=1
UpdateDivider=120
